# Generated by Django 3.0.5 on 2020-04-05 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('name',), 'verbose_name': 'บทความ', 'verbose_name_plural': 'เนื้อหาบทความ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'หมวดหมู่บทความ', 'verbose_name_plural': 'ข้อมูลประเภทบทความ'},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
