# Generated by Django 3.0.5 on 2020-04-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0003_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'เมือง'},
        ),
    ]
