# Generated by Django 3.0.5 on 2020-04-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0004_auto_20200407_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readlist_id', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'readlist',
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='ReadList_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.Article')),
                ('readlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.ReadList')),
            ],
            options={
                'db_table': 'บทความในคลัง',
                'ordering': ('article',),
            },
        ),
    ]
