# Generated by Django 3.0.5 on 2020-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0005_readlist_readlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
