# Generated by Django 3.0.5 on 2020-04-14 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagesite', '0006_article_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'หมวดหมู่บทความ', 'verbose_name_plural': 'ประเภทบทความ'},
        ),
        migrations.AlterModelOptions(
            name='readlist',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'กล่อง readlist'},
        ),
        migrations.AlterModelOptions(
            name='readlist_item',
            options={'ordering': ('article',), 'verbose_name_plural': 'บทความในกล่อง readlist'},
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=120)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('dratf', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.Category')),
            ],
        ),
    ]
