# Generated by Django 3.0.5 on 2020-04-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0011_categorypost_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadList_Item',
        ),
    ]
