# Generated by Django 3.0.5 on 2020-04-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0012_delete_readlist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadList_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.Article')),
                ('readlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.ReadList')),
            ],
            options={
                'verbose_name_plural': 'บทความในกล่อง readlist',
                'db_table': 'บทความในคลัง',
                'ordering': ('article',),
            },
        ),
    ]
