# Generated by Django 3.0.5 on 2020-04-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0013_readlist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadList_Item_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.Post')),
                ('readlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.ReadList')),
            ],
            options={
                'verbose_name_plural': 'post ในกล่อง readlist',
                'db_table': 'post ในคลัง',
                'ordering': ('post',),
            },
        ),
    ]
