# Generated by Django 3.0.5 on 2020-04-22 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0014_readlist_item_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('dratf', 'สร้างดราฟต์'), ('published', 'เผยแพร่')], default='published', max_length=20),
        ),
    ]
