# Generated by Django 3.0.5 on 2020-04-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0017_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
