# Generated by Django 3.0.5 on 2020-04-25 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagesite', '0018_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_article',
            field=models.ManyToManyField(blank=True, related_name='likes_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
