# Generated by Django 3.0.5 on 2020-04-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0019_auto_20200425_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='likes_article',
            new_name='likes',
        ),
    ]
