# Generated by Django 3.0.5 on 2020-04-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0021_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pagesite.CommentPost'),
        ),
    ]
