# Generated by Django 3.0.5 on 2020-04-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0023_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesite.Post'),
        ),
    ]
