# Generated by Django 3.0.5 on 2020-04-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0024_auto_20200429_0429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
