# Generated by Django 3.0.5 on 2020-04-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0026_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
