# Generated by Django 3.0.5 on 2020-04-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0028_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
