# Generated by Django 3.0.5 on 2020-04-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0029_remove_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readlist_item',
            name='article',
        ),
        migrations.RemoveField(
            model_name='readlist_item',
            name='readlist',
        ),
        migrations.RemoveField(
            model_name='readlist_item_post',
            name='post',
        ),
        migrations.RemoveField(
            model_name='readlist_item_post',
            name='readlist',
        ),
        migrations.DeleteModel(
            name='ReadList',
        ),
        migrations.DeleteModel(
            name='ReadList_Item',
        ),
        migrations.DeleteModel(
            name='ReadList_Item_Post',
        ),
    ]
