# Generated by Django 3.0.5 on 2020-04-29 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagesite', '0030_auto_20200430_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='savelist',
            field=models.ManyToManyField(blank=True, related_name='savelist_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
