# Generated by Django 3.0.5 on 2020-04-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0032_auto_20200430_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='savelist',
        ),
    ]
