# Generated by Django 3.0.5 on 2020-04-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0034_commentarticle_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentarticle',
            old_name='post',
            new_name='article',
        ),
    ]
