# Generated by Django 3.0.5 on 2020-05-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesite', '0036_categorymasalah_commentmasalah_masalah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masalah',
            name='category',
        ),
        migrations.RemoveField(
            model_name='masalah',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('dratf', 'สร้างฉบับร่าง'), ('published', 'เผยแพร่สาธารณะ')], default='published', max_length=20),
        ),
        migrations.DeleteModel(
            name='CommentMasalah',
        ),
        migrations.DeleteModel(
            name='Masalah',
        ),
    ]
